language: php
php:
- '7.0'
- '7.1'
script:
- php build.php
- phpunit
deploy:
  provider: releases
  api_key:
    secure: sLJ0KiLx5oFXVClrHAS0r9JwAF1UQNqgJ3BdPnErBbqg+Pry6rDTxcLAK3gwmayvkKrU1wLZ5AxEUCQKQ7x3hckKEebeZL09pfUwegsc4MXE0WzRzmF/b2YdQogR0b3K0o1WmrJrGm51Jedc4H3Osy2mbu10VnGvCJRTl/kCKhxmrKeWUA0isT4YHpP5Xj4tB9YHU9jmcxL5RzG3uQ0MyszbCR//1yfx99BubTPSByUGywZGXyM3ymSMDjrvwWW+mfZTcz8t9hmMQYNiz4UwLSXDQoKHbIpXT0HylEdYfFtVL8IcmStqj/NJU1QIHGx52uXVydcc9/HcE3o9R3NGDWVd0qjmMqgh4eRlqvnKf/rb2EVk0JDtlacJ7/VchYEp9xKlvUcAsiYMnAeSBLn1qy6dTK74jlFOD3mvS3zeBbmEsCrMOR3w6y2bYxG8VrfDngLauPkX1Un4wCpVHntxKXqHy2LW/MQrlyoaPHoeWM7EIhHRAmOeVcCcWpFem4NNHn6ciufqUDYAAw0YW5QkmU8fs31AGULEWl+FqlNyWblPHLU4dqC4FHI9c9Ij1bbnE7le3NmiUvVSsV0MH/Sb3RsbF093CeVnkTdvTwiTMozRlKK4ui6+9NF5jHB/K7uqxrpfhqURRnlrG1cw5b4zUMRAT/21bawTrtXa5r/4DC4=
  file: reqc.phar
  skip_cleanup: true
  on:
    tags: true
